name: Automatic Version Checks
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  checkAppVersions:
    name: Check for current app versions and re-build site if they changed
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Query releases from MissingCore Music
        id: music_versions
        run: |
          echo "MUSIC_LATEST_TAG=$(gh release list \
            --repo MissingCore/Music \
            --exclude-drafts \
            --exclude-pre-releases \
            --limit 1 \
            --json tagName \
            --jq '.[0].tagName')" >> $GITHUB_OUTPUT
          echo "MUSIC_RECENT_TAG=$(gh release list \
            --repo MissingCore/Music \
            --exclude-drafts \
            --limit 1 \
            --json tagName \
            --jq '.[0].tagName')" >> $GITHUB_OUTPUT
          echo "Latest Tag: ${{ steps.music_versions.outputs.MUSIC_LATEST_TAG }}, Most Recent Tag: ${{ steps.music_versions.outputs.MUSIC_RECENT_TAG }}"
